### ISSUE TITLE
Running the program reports an error, please help

### ISSUE THREAD

**Issue by zArvin6808** [instantX-research/CSGO#16]
D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/TTPlanet/TTPLanet_SDXL_Controlnet_Tile_Realistic/resolve/37f1c4575b543fb2036e39f5763d082fdd135318/diffusion_pytorch_model.safetensors

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\diffusers\utils\hub_utils.py", line 308, in _get_model_file
    model_file = hf_hub_download(
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\file_download.py", line 1240, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\file_download.py", line 1303, in _hf_hub_download_to_cache_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\file_download.py", line 1751, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\file_download.py", line 1673, in get_hf_file_metadata
    r = _request_wrapper(
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\file_download.py", line 376, in _request_wrapper
    response = _request_wrapper(
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\file_download.py", line 400, in _request_wrapper
    hf_raise_for_status(response)
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\utils\_errors.py", line 315, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-6724f257-47941b4f5a94e9f31faaa83f;2430033f-1c76-46de-93de-8d07a33f54a0)

Entry Not Found for url: https://huggingface.co/TTPlanet/TTPLanet_SDXL_Controlnet_Tile_Realistic/resolve/37f1c4575b543fb2036e39f5763d082fdd135318/diffusion_pytorch_model.safetensors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\CSGO\CSGO\gradio\app.py", line 30, in <module>
    controlnet = ControlNetModel.from_pretrained(controlnet_path, torch_dtype=weight_dtype, use_safetensors=True)
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\diffusers\models\modeling_utils.py", line 774, in from_pretrained
    raise e
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\diffusers\models\modeling_utils.py", line 758, in from_pretrained
    model_file = _get_model_file(
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\diffusers\utils\hub_utils.py", line 337, in _get_model_file
    raise EnvironmentError(
OSError: TTPlanet/TTPLanet_SDXL_Controlnet_Tile_Realistic does not appear to have a file named diffusion_pytorch_model.safetensors.

**Comment by xingp-ng** [comment]
> D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`. warnings.warn( Traceback (most recent call last): File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\utils_errors.py", line 304, in hf_raise_for_status response.raise_for_status() File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\requests\models.py", line 1024, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/TTPlanet/TTPLanet_SDXL_Controlnet_Tile_Realistic/resolve/37f1c4575b543fb2036e39f5763d082fdd135318/diffusion_pytorch_model.safetensors
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\diffusers\utils\hub_utils.py", line 308, in _get_model_file model_file = hf_hub_download( File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\utils_deprecation.py", line 101, in inner_f return f(*args, **kwargs) File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\utils_validators.py", line 114, in _inner_fn return fn(*args, **kwargs) File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\file_download.py", line 1240, in hf_hub_download return _hf_hub_download_to_cache_dir( File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\file_download.py", line 1303, in _hf_hub_download_to_cache_dir (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error( File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\file_download.py", line 1751, in _get_metadata_or_catch_error metadata = get_hf_file_metadata( File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\utils_validators.py", line 114, in _inner_fn return fn(*args, **kwargs) File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\file_download.py", line 1673, in get_hf_file_metadata r = _request_wrapper( File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\file_download.py", line 376, in _request_wrapper response = _request_wrapper( File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\file_download.py", line 400, in _request_wrapper hf_raise_for_status(response) File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\utils_errors.py", line 315, in hf_raise_for_status raise EntryNotFoundError(message, response) from e huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-6724f257-47941b4f5a94e9f31faaa83f;2430033f-1c76-46de-93de-8d07a33f54a0)
> 
> Entry Not Found for url: https://huggingface.co/TTPlanet/TTPLanet_SDXL_Controlnet_Tile_Realistic/resolve/37f1c4575b543fb2036e39f5763d082fdd135318/diffusion_pytorch_model.safetensors.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "D:\AI\CSGO\CSGO\gradio\app.py", line 30, in controlnet = ControlNetModel.from_pretrained(controlnet_path, torch_dtype=weight_dtype, use_safetensors=True) File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\utils_validators.py", line 114, in _inner_fn return fn(*args, **kwargs) File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\diffusers\models\modeling_utils.py", line 774, in from_pretrained raise e File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\diffusers\models\modeling_utils.py", line 758, in from_pretrained model_file = _get_model_file( File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\huggingface_hub\utils_validators.py", line 114, in _inner_fn return fn(*args, **kwargs) File "D:\AI\CSGO\CSGO\runtime\lib\site-packages\diffusers\utils\hub_utils.py", line 337, in _get_model_file raise EnvironmentError( OSError: TTPlanet/TTPLanet_SDXL_Controlnet_Tile_Realistic does not appear to have a file named diffusion_pytorch_model.safetensors.

you can do this:
git clone https://huggingface.co/TTPlanet/TTPLanet_SDXL_Controlnet_Tile_Realistic
mv TTPLanet_SDXL_Controlnet_Tile_Realistic/TTPLANET_Controlnet_Tile_realistic_v2_fp16.safetensors TTPLanet_SDXL_Controlnet_Tile_Realistic/diffusion_pytorch_model.safetensors
